auth/urls.py
from django.urls import path
from .views import login_view, logout_view, register_view


app_name = 'auth'


urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('article.urls', namespace='article')),
    path('auth/', include('auth.urls', namespace='auth')),
    path('recipe/', include('recipe.urls', namespace='recipe'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipe/urls.py
from django.urls import path
from .views import recipe_list, recipe_detail, my_recipe_list, recipe_create, recipe_update, recipe_delete, recipe_ingredient_create, recipe_ingredient_edit, recipe_ingredient_delete

app_name = 'recipe'


urlpatterns = [
    path('list/', recipe_list, name='list'),
    path('list/my/', my_recipe_list, name='my-list'),
    path('detail/<slug:slug>/', recipe_detail, name='detail'),
    path('create/', recipe_create, name='create'),
    path('update/<slug:slug>', recipe_update, name='update'),
    path('delete/<slug:slug>', recipe_delete, name='delete'),
    path('<slug:slug>/ingridient/create/', recipe_ingredient_create, name='ingredient_create'),
    path('<slug:slug>/ingridient/edit/<int:pk>', recipe_ingredient_edit, name='ingredient_edit'),
    path('<slug:slug>/ingridient/delete/<int:pk>', recipe_ingredient_delete, name='ingredient_delete'),
]

recipe/models.py
import random

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import pre_save
from django.utils.text import slugify


class Tag(models.Model):
    title = models.CharField(max_length=221)

    def __str__(self):
        return self.title


class Recipe(models.Model):
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    title = models.CharField(max_length=221)
    tag = models.ManyToManyField(Tag)
    slug = models.SlugField(unique=True, editable=False, null=True)
    image = models.ImageField(upload_to='recipe/', null=True, blank=True)
    description = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Ingredient(models.Model):
    UNIT = (
        (0, "Kilogram"),
        (1, "Gram"),
        (2, "Litre"),
        (3, "Piece")
    )
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name="ingredients")
    title = models.CharField(max_length=221)
    quantity = models.DecimalField(max_digits=10, decimal_places=2)
    unit = models.IntegerField(choices=UNIT, default=1)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.title


def recipe_pre_save(sender, instance, *args, **kwargs):
    if instance.slug is None:
        instance.slug = slugify(instance.title + str(random.randint(1000, 9999)))


pre_save.connect(recipe_pre_save, sender=Recipe)

recipe/forms.py
from django import forms
from .models import Recipe, Ingredient


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ["title", 'image', 'author', 'description', 'tag']
        exclude = ['author']

    def __init__(self, *args, **kwargs):
        super(RecipeForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({
            "class": "form-control",
            "id": "recipe_title",
            "placeholder": "Title"
        })
        self.fields['image'].widget.attrs.update({
            "class": "form-control",
            "id": "recipe_image",
        })
        self.fields['description'].widget.attrs.update({
            "class": "form-control",
            "id": "recipe_description",
            "placeholder": "Description",
            "rows": "4"
        })

        self.fields['tag'].widget.attrs.update({
            "class": "form-select",
            "id": "recipe_tags",
        })

    def clean_title(self):
        title = self.cleaned_data['title']
        return title.capitalize()


class IngredientEditForm(forms.ModelForm):
    class Meta:
        model = Ingredient
        fields = ["title", "recipe", "quantity", "is_active", "unit"]
        exclude = ['recipe']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({
            "class": "form-control",
            "id": "ingredient_title",
            "placeholder": "Title"
        })
        self.fields['quantity'].widget.attrs.update({
            "class": "form-control",
            "id": "ingredient_quantity",
            "placeholder": "Quantity"
        })
        self.fields['unit'].widget.attrs.update({
            "class": "form-select",
            "id": "ingredient_unit",
        })
        self.fields['is_active'].widget.attrs.update({
            "id": "flexSwitchCheckChecked ",
            "class": "form-check-input",
            "type": "checkbox",
            "role": "switch",
        })


class IngredientForm(IngredientEditForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['is_active'].widget.attrs.update({
            "checked": "checked"
        })

recipe/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from .models import Recipe, Tag, Ingredient
from .forms import RecipeForm, IngredientForm, IngredientEditForm
from django.contrib import messages
from django.db.models import Q
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator


def recipe_list(request):
    tag = request.GET.get('tag')
    q = request.GET.get('q')
    q_condition = Q()
    if q:
        q_condition = Q(title__icontains=q)
    tag_condition = Q()
    if tag:
        tag_condition = Q(tag__title=tag)
    recipes = Recipe.objects.filter(q_condition, tag_condition).order_by('-id')

    paginator = Paginator(recipes, 3)
    page_number = request.GET.get("page")
    page_qs = paginator.get_page(page_number)
    context = {
        'object_list': page_qs
    }

    return render(request, 'recipe/index.html', context)


def my_recipe_list(request):
    recipes = Recipe.objects.filter(author_id=request.user.id).order_by('-id')
    tag = request.GET.get('tag')
    if tag:
        recipes = recipes.filter(tag__title=tag)

    context = {
        'object_list': recipes
    }

    return render(request, 'recipe/index.html', context)


def recipe_detail(request, slug):
    recipe = get_object_or_404(Recipe, slug=slug)
    is_author_lookup = Q(is_active=True)
    if request.user == recipe.author:
        is_author_lookup = Q()
    ingredients = Ingredient.objects.filter(Q(recipe_id=recipe.id) & is_author_lookup)
    is_author = request.user == recipe.author
    context = {
        "object": recipe,
        'ingredients': ingredients,
        "is_author": is_author
    }

    return render(request, 'recipe/detail.html', context)


def recipe_create(request):
    if not request.user.is_authenticated:
        messages.info(request, "You should log in")
        reverse_url = reverse('auth:login') + "?next=" + request.path
        return redirect(reverse_url)
    form = RecipeForm()
    if request.method == 'POST':
        form = RecipeForm(request.POST, files=request.FILES)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.author_id = request.user.id
            obj.save()
            form.save_m2m()
            detail_url = reverse('recipe:detail', args = [obj.slug])
            return redirect(detail_url)
    context = {
        'form': form
    }
    return render(request, 'recipe/create.html', context)


def recipe_update(request, slug):
    instance = get_object_or_404(Recipe, slug=slug)
    form = RecipeForm(instance=instance)
    if request.method == 'POST':
        form = RecipeForm(data=request.POST, files=request.FILES, instance=instance)
        if form.is_valid():
            form.save()
            detail_url = reverse('recipe:detail', kwargs={"slug": instance.slug})
            return redirect(detail_url)
    context = {
        "form": form,
        "header": "Recipe update"
    }
    return render(request, 'recipe/create.html', context)


def recipe_delete(request, slug):
    recipe = get_object_or_404(Recipe, slug=slug)
    if request.method == "POST":
        if not request.user == recipe.author:
            messages.warning(request, "You cannot delete")
            return redirect(reverse('recipe:detail', args=[recipe.slug]))
        recipe.delete()
        return redirect("recipe:list")
    ctx = {
        "object": recipe
    }
    return render(request, 'recipe/delete.html', ctx)


def recipe_ingredient_create(request, slug):
    recipe = get_object_or_404(Recipe, slug=slug)
    form = IngredientForm()
    if recipe.author != request.user:
        messages.error(request, "You should log in")
        return redirect('auth:login')
    if request.method == "POST":
        form = IngredientForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.recipe = recipe
            obj.save()
            reverse_url = reverse('recipe:detail', args=[recipe.slug])
            messages.success(request, "You create new one")
            return redirect(reverse_url)

    ctx = {
        "form": form,
        "recipe": recipe
    }
    return render(request, "recipe/recipe_ingrdient_create.html", ctx)


def recipe_ingredient_edit(request, slug, pk, *args, **kwargs):
    recipe = get_object_or_404(Recipe, slug=slug)
    instance = get_object_or_404(Ingredient, id=pk)
    if instance not in recipe.ingredients.all():
        raise ObjectDoesNotExist(f"{instance.title} does not exist in {recipe.title}")
    if recipe.author != request.user:
        messages.error("You should log in")
        return redirect('auth:login')
    form = IngredientEditForm(instance=instance)
    if request.method == 'POST':
        form = IngredientEditForm(data=request.POST, instance=instance)
        if form.is_valid():
            form.save()
            reverse_url = reverse('recipe:detail', args=[slug])
            return redirect(reverse_url)

    ctx = {
        'form': form,
        "recipe": recipe,
        "title": "Change ingredient belong to"
    }

    return render(request, 'recipe/recipe_ingrdient_create.html', ctx)


def recipe_ingredient_delete(request, *args, **kwargs):
    recipe = get_object_or_404(Recipe, slug=kwargs['slug'])
    reverse_url = reverse('recipe:detail', args=[kwargs['slug']])
    instance = get_object_or_404(Ingredient, id=kwargs['pk'])
    if instance not in recipe.ingredients.all():
        raise ObjectDoesNotExist(f"{instance.title} does not exist in {recipe.title}")
    if recipe.author != request.user:
        messages.error("You should log in")
        return redirect('auth:login')
    if request.method == 'POST':
        instance.delete()
        return redirect(reverse_url)
    ctx = {
        "object": instance,
        "recipe": recipe
    }
    return render(request, 'recipe/ingredient_delete.html', ctx)

templates/recipe/create.html
{% extends 'base.html' %}


{% block title %}
	Recipe Create
{% endblock %}

{% block header %}
    {% if header %}
    	<h1>{{ header }}</h1>
    {% else %}
	    <h1>Recipe Create</h1>
    {% endif %}
{% endblock %}

{% block content %}
    {% block primary_link %}
        <span>
            <a class="text-decoration-none text-primary " href="{% url 'recipe:list' %}">Recipes</a>
        </span>/ Add New Create
    {% endblock %}

    <div class="row d-flex justify-content-center">
        <div class="col-md-6">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                  <div class="mb-3 row">
                    <label for="recipe_title" class="col-sm-2 col-form-label">Title: </label>
                    <div class="col-sm-10">
                      {{ form.title }}
                    </div>
                  </div>
                  <div class="mb-3 row">
                    <label for="recipe_image" class="col-sm-2 col-form-label">Image: </label>
                    <div class="col-sm-10">
                      {{ form.image }}
                    </div>
                  </div>
                <div class="mb-3 row">
                    <label for="recipe_description" class="col-sm-2 col-form-label">Description: </label>
                    <div class="col-sm-10">
                      {{ form.description }}
                    </div>
                  </div>
                <div class="mb-3 row">
                    <label for="recipe_tags" class="col-sm-2 col-form-label">Tags: </label>
                    <div class="col-sm-10">
                      {{ form.tag }}
                    </div>
                  </div>
                <div class="buttons d-flex gap-2 justify-content-end">
                    <button class="btn btn-primary" type="submit">Save</button>
                    <button class="btn btn-warning" type="reset">Reset fields</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/recipe/delete.html
{% extends "base.html" %}

{% block title %}Recipe Delete{% endblock %}

{% block header %}
    <h1>Recipe Deleting</h1>
{% endblock %}

{% block content %}
    {% block primary_link %}
        <div>
            <span>
                <a href="{% url 'recipe:list' %}">Recipes</a>
            </span>/ <span>Delete</span>
        </div>
    {% endblock %}
    <h3 class="text-dark mt-3">
        Do you want to delete <span class="text-danger">"{{ object.title }}"</span>?
    </h3>
     <form method="post" class="mt-3">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Delete</button>
            <a href="{% url "recipe:detail" object.slug %}" class="btn btn-secondary">Cancel</a>
     </form>
{% endblock %}

templates/recipe/detail.html
{% extends 'base.html' %}

{% block title %}
	Recipe Detail
{% endblock %}

{% block header %}
    <h1>Recipe detail</h1>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
        <div class="card mb-3 mt-4">
          <div class="row g-0">
            <div class="col-md-4">
              <img src="{{ object.image.url }}" class="img-fluid rounded-start" alt="...">
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title">{{ object.title }}</h5>
                <p class="card-text">{{ object.description }}</p>
                <p>
                    {% for foo in object.tag.all  %}
                        <a href="#">#{{ foo.title }}</a>
                    {% endfor %}
                </p>
                <p class="card-text"><small class="text-body-secondary">{{ object.created_date }}</small></p>
              </div>
                {% if is_author %}
                	<div class="card-button p-2">
                      <a href="{% url "recipe:update" object.slug %}" class="btn btn-secondary btn-lg">Editing Recipe</a>
                      <a href="{% url "recipe:delete" object.slug %}" class="btn btn-danger btn-lg">Deleting recipe</a>
                      <a href="{% url "recipe:ingredient_create" object.slug %}" class="btn btn-primary btn-lg">Adding New Ingredient</a>
                  </div>
                {% endif %}

            </div>
          </div>
    </div>
        </div>
    </div>

    <div class="row mt-2 mb-4">
    {% for ingredient in ingredients %}
    	<div class="col-sm-6 mb-3">
            <div class="card {% if not ingredient.is_active %}bg-warning{% endif %}">
              <div class="card-body">
                <h5 class="card-title">{{ ingredient.title }}</h5>
                <p class="card-text">{{ ingredient.quantity }} - {{ ingredient.get_unit_display }}</p>
                <a href="{% url "recipe:ingredient_edit" object.slug ingredient.id %}" class="btn btn-secondary">Editing Ingredient</a>
                <a href="{% url "recipe:ingredient_delete" object.slug ingredient.id %}" class="btn btn-danger">Deleting Ingredient</a>
              </div>
            </div>
          </div>
    {% endfor %}


    </div>

{% endblock %}

templates/recipe/index.html
{% extends 'base.html' %}

{% block title %}
	Recipes
{% endblock %}

{% block header %}
    <div class="d-flex justify-content-between mt-5 align-items-center">
        <h1>Recipe list</h1>
        <form class="row g-3" action="{% url "recipe:list" %}">
            <div class="col-auto">
                <input type="search" name="q" class="form-control" id="search" placeholder="Search...">
            </div>
            <div class="col-auto">
                <button type="submit" class="btn btn-primary">Search</button>
            </div>
        </form>
        <a href="{% url "recipe:create" %}" class="btn btn-primary d-flex text-center justify-content-center">+Add New Recipe</a>

    </div>
{% endblock %}

{% block content %}
    <div class="row mt-5">
    {% if object_list %}
        {% for object in object_list %}
        	<div class="col-md-4">
                <div class="card mb-3">
                  <img src="{{ object.image.url }}" class="card-img-top" alt="{{ object.title }}">
                  <div class="card-body">
                    <h5 class="card-title">{{ object.title }}</h5>
                    <h6 class="card-title">Author: {{ object.author }}</h6>
                    <p class="card-text">{{ object.description }}</p>
                      <p>
                        {% for foo in object.tag.all  %}
                            <a href="?tag={{ foo.title }}">#{{ foo.title }}</a>
                        {% endfor %}
                    </p>
                    <p class="card-text"><small class="text-body-secondary">{{ object.created_date }}</small></p>
                    <a href="{% url 'recipe:detail' object.slug %}" class="btn btn-primary">See more</a>
                  </div>
                </div>
            </div>
        {% endfor %}
        <nav aria-label="Page navigation example">
          <ul class="pagination justify-content-center">

            <li class="page-item {% if not object_list.has_previous %}disabled{% endif %}">
              <a class="page-link" href="{% if object_list.has_previous %}?page={{ object_list.previous_page_number }}{% endif %}">Previous</a>
            </li>
              {% for object in object_list.paginator.page_range %}
                <li class="page-item"><a class="page-link {% if object_list.number == object %}active{% endif %}" href="?page={{ object }}">{{ object }}</a></li>
              {% endfor %}

            <li class="page-item {% if not object_list.has_next %}disabled{% endif %}">
              <a class="page-link" href="{% if object_list.has_next %}?page={{ object_list.next_page_number }}{% endif %}">Next</a>
            </li>
          </ul>
        </nav>
    {% else %}
        <h1 class="text-center">Hech narsa topilmadi</h1>
    {% endif %}
    </div>
{% endblock %}

templates/recipe/ingredient_delete.html
{% extends 'base.html' %}

{% block title %}
	Ingredient Delete
{% endblock %}

{% block header %}
    <h1>Ingredient Delete</h1>
{% endblock %}


{% block content %}
    <div class="col-md-6 offset-md-3 mt-4">
        <h3>Are you sure to delete <span class="text-danger">"{{ object.title }}"</span></h3>
    </div>
    <form method="post">
        {% csrf_token %}
        <div class="buttons d-flex gap-3 justify-content-end">
            <button type="submit" class="btn btn-danger">Yes, I am sure</button>
            <a href="{% url "recipe:detail" recipe.slug  %}" class="btn btn-secondary">No, Thanks</a>
        </div>
    </form>
{% endblock %}

templates/recipe/recipe_ingrdient_create.html
{% extends "base.html" %}

{% block title %}Create New Ingredient{% endblock %}

{% block header%}
    {% if title %}
        <h1>{{ title }} "{{ recipe.title }}</h1>
    {% else %}
    <h1>Add new Ingredient "{{ recipe.title }}"</h1>
    {% endif %}
{% endblock %}

{% block content %}
    <div class="col-md-6 offset-md-3 mt-5">
        <form method="post">
            {% csrf_token %}
            <div class="mb-3 row">
                        <label for="ingredient_title" class="col-sm-2 col-form-label">Title: </label>
                        <div class="col-sm-10">
                          {{ form.title }}
                        </div>
                      </div>
            <div class="mb-3 row">
                        <label for="ingredient_quantity" class="col-sm-2 col-form-label">Quantity: </label>
                        <div class="col-sm-10">
                          {{ form.quantity }}
                        </div>
                      </div>
            <div class="mb-3 row">
                        <label for="ingredient_unit" class="col-sm-2 col-form-label">Unit: </label>
                        <div class="col-sm-10">
                          {{ form.unit }}
                        </div>
                      </div>
            <div class="form-check form-switch">
                {{ form.is_active }}
              <label class="form-check-label" for="flexSwitchCheckChecked">Is active</label>
            </div>

            <div class="buttons d-flex justify-content-end gap-2">
                <button type="submit" class="btn btn-primary">Save</button>
                <button type="reset" class="btn btn-warning">Reset</button>
                <a href="{% url "recipe:detail" recipe.slug  %}" class="btn btn-secondary">Cancel</a>
            </div>
        </form>
    </div>
{% endblock %}