article/urls.py
from django.urls import path
from .views import article_list, article_detail, article_create, article_create_form, article_edit, article_delete

app_name = 'article'

urlpatterns = [
    path('', article_list, name='article_list'),
    path('article/<slug:slug>/', article_detail, name='article_detail'),
    path('artcile/create/', article_create, name='create'),
    path('article/create/form/', article_create_form, name='create-form'),
    path('article/change/<int:pk>/', article_edit, name='change'),
    path('article/delete/<int:pk>/', article_delete, name='delete'),
]

auth/urls.py
from django.urls import path
from .views import login_view, logout_view, register_view


app_name = 'auth'


urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('article.urls', namespace='article')),
    path('auth/', include('auth.urls', namespace='auth')),
    path('recipe/', include('recipe.urls', namespace='recipe'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipe/urls.py
from django.urls import path
from .views import recipe_list, recipe_detail, my_recipe_list, recipe_create, recipe_update, recipe_delete, recipe_ingredient_create, recipe_ingredient_edit, recipe_ingredient_delete

app_name = 'recipe'


urlpatterns = [
    path('list/', recipe_list, name='list'),
    path('list/my/', my_recipe_list, name='my-list'),
    path('detail/<slug:slug>/', recipe_detail, name='detail'),
    path('create/', recipe_create, name='create'),
    path('update/<slug:slug>', recipe_update, name='update'),
    path('delete/<slug:slug>', recipe_delete, name='delete'),
    path('<slug:slug>/ingridient/create/', recipe_ingredient_create, name='ingredient_create'),
    path('<slug:slug>/ingridient/edit/<int:pk>', recipe_ingredient_edit, name='ingredient_edit'),
    path('<slug:slug>/ingridient/delete/<int:pk>', recipe_ingredient_delete, name='ingredient_delete'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Try django{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'style/index.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
<div class="container">

{% include 'navbar.html' %}

{% include 'messages.html' %}

{% block header %}

{% endblock %}

{% block content %}
 <div class="mb-3">
    {% block primary_link %}
        <span>
            <a class="text-decoration-none text-primary " href="{% url 'article:article_list' %}">Articles</a>
        </span>/
    {% endblock %}
 </div>
{% endblock %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

templates/messages.html
{% for message in messages %}
    {% if message.tags == 'success' %}
    <div class="alert alert-success" role="alert">
        {{ message }}
    </div>
    {% elif message.tags == 'error' %}
    <div class="alert alert-danger" role="alert">
      {{ message }}
    </div>
    {% elif message.tags == 'warning' %}
    <div class="alert alert-warning" role="alert">
      {{ message }}
    </div>
    {% elif message.tags == 'info' %}
    <div class="alert alert-info" role="alert">
      {{ message }}
    </div>
    {% elif message.tags == 'debug' %}
    <div class="alert alert-dark" role="alert">
      {{ message }}
    </div>
    {% endif %}
{% endfor %}

templates/navbar.html
{% load static %}

<div>
     <nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
        <img class="image" style="width: 70px" src="{% static 'logo/photo_2022-09-30_19-10-59.jpg' %}" alt="">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'article:article_list' %}">Article List</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'article:create' %}">Add Article</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'article:create-form' %}">Article Create Form</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'recipe:list' %}">Recipes</a>
        </li>
          {% if request.user.is_authenticated %}
          <li class="nav-item">
          <a class="nav-link" href="{% url 'recipe:my-list' %}">My Recipes</a>
        </li>
          {% endif %}

      </ul>
      <form class="d-flex align-items-center" role="search" action="{% url 'article:article_list' %}" method="get">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
        <button class="btn btn-outline-success mr-3" type="submit">Search</button>
          {% if request.user.is_authenticated %}
              <h1 class="ms-1 text-uppercase ">{{ request.user.username }}</h1>
              <a href="{% url 'auth:logout' %}" class="btn btn-outline-danger">Logout</a>
          {% else %}
            <a href="{% url 'auth:login' %}" class="btn btn-outline-primary ml-3" type="submit">Login</a>
          {% endif %}
      </form>

    </div>
  </div>
</nav>
 </div>