article/urls.py
from django.urls import path
from .views import article_list, article_detail, article_create, article_create_form, article_edit, article_delete

app_name = 'article'

urlpatterns = [
    path('', article_list, name='article_list'),
    path('article/<slug:slug>/', article_detail, name='article_detail'),
    path('artcile/create/', article_create, name='create'),
    path('article/create/form/', article_create_form, name='create-form'),
    path('article/change/<int:pk>/', article_edit, name='change'),
    path('article/delete/<int:pk>/', article_delete, name='delete'),
]

auth/urls.py
from django.urls import path
from .views import login_view, logout_view, register_view


app_name = 'auth'


urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('article.urls', namespace='article')),
    path('auth/', include('auth.urls', namespace='auth')),
    path('recipe/', include('recipe.urls', namespace='recipe'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.db.models.signals import pre_save, post_save
from django.db.models import Q


class ArticleQuerySet(models.QuerySet):
    def search(self, query=None):
        if query is None or query=="":
            return self.all()
        try:
            int(query)
        except:
            lookups = Q(title__icontains=query)
        else:
            lookups = Q(title__icontains=query) | Q(id=query)
        return self.filter(lookups)


class ArticleManager(models.Manager):
    def get_queryset(self):
        return ArticleQuerySet(self.model, using=self._db)

    def search(self, query=None):
        return self.get_queryset().search(query)


class Article(models.Model):
    title = models.CharField(max_length=222)
    slug = models.SlugField(null=True, unique=True, editable=False)
    content = models.TextField()
    image = models.ImageField(upload_to='article/', null=True, blank=True)
    modified_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    objects = ArticleManager()

    def __str__(self):
        return self.title

    # def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
    #     if self.slug is None:
    #         self.slug = slugify(self.title)
    #     super().save(force_insert=False, force_update=False, using=None, update_fields=None)

    @property
    def get_absolute_url(self):
        return reverse('article:article_detail', args=[self.id])


def article_pre_save(sender, instance, *args, **kwargs):
    if instance.slug is None:
        instance.slug = slugify(instance.title)


def article_post_save(sender, instance, created, *args, **kwargs):
    if instance.slug is None:
        instance.slug = slugify(instance.title)
        instance.save()


pre_save.connect(article_pre_save, sender=Article)
post_save.connect(article_post_save, sender=Article)

article/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'image', 'content']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({
            'placeholder': 'title',
            'class': 'form-control'
        })
        self.fields['image'].widget.attrs.update({
            'class': 'form-control'
        })
        self.fields['content'].widget.attrs.update({
            'placeholder': 'content',
            'cols': 60,
            'rows': 5,
            'class': 'form-control'
        })

    def clean_title(self):
        if self.cleaned_data['title'].replace(" ", "").isalnum():
            print(self.cleaned_data['title'])
            return self.cleaned_data['title']
        raise ValidationError('Title must be alpha numeric')

article/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from .models import Article
from .forms import ArticleForm
from django.contrib import messages
from django.db.models import Q
from django.contrib.auth.decorators import login_required, permission_required
from django.core.paginator import Paginator
# Create your views here.


def article_list(request):
    articles = Article.objects.all()
    old_articles = articles
    query = request.GET.get('q')
    articles = Article.objects.search(query=query)
    paginator = Paginator(articles, 3)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    # if query:
    #     # articles = Article.objects.filter(title__icontains=query)
    #     articles = Article.objects.filter(Q(title__icontains=query) | Q(content__icontains=query))
    context = {
        "object_list": page_obj,
        "old_articles_list": old_articles
    }
    return render(request, 'article/index.html', context)


def article_detail(request, slug):
    article = Article.objects.get(slug=slug)
    context = {
        "object_detail": article
    }
    return render(request, 'article/detail.html', context)


def article_create(request):
    context = {
        'created': False
    }
    if request.method == 'POST':
        title = request.POST.get('title')
        content = request.POST.get('content')
        image = request.POST.get('image')
        obj = Article.objects.create(title=title, content=content, image=image)
        context['created'] = True
        context['object'] = obj
        messages.success(request, "Article create")

    return render(request, 'article/create.html', context)


def article_create_form(request):
    form = ArticleForm()
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            obj = form.save()
            reverse_url = reverse('article:article_detail', args=[obj.id])
            messages.success(request, "Article create")
            return redirect(reverse_url)
    context = {
        'form': form
    }

    return render(request, 'article/create-form.html', context)


def article_create_form_(request):
    form = ArticleForm(request.POST or None, files=request.FILES)
    if form.is_valid():
        obj = form.save()
        reverse_url = reverse('article:article_detail', args=[obj.id])
        return redirect(reverse_url)
    context = {
        'form': form
    }

    return render(request, 'article/create-form.html', context)


def article_edit(request, pk):
    obj = Article.objects.get(id=pk)
    form = ArticleForm(instance=obj)
    if request.method == 'POST':
        form = ArticleForm(request.POST, instance=obj, files=request.FILES)
        if form.is_valid():
            form.save()
            reverse_url = reverse('article:change', kwargs={"pk": obj.id})
            messages.success(request, "Article Edit")
            return redirect(reverse_url)

    context = {
        'form': form,
        'object': obj,
    }
    return render(request, 'article/edit.html', context)


@login_required(login_url="auth:login")
@permission_required(perm="request.user.is_admin", login_url='/')
def article_delete(request, pk):
    obj = get_object_or_404(Article, id=pk)
    if request.method == 'POST':
        obj.delete()
        messages.error(request, "Article delete")
        return redirect('article:article_list')
    context = {
        'object': obj
    }

    return render(request, 'article/delete.html', context)

templates/article/create-form.html
{% extends 'base.html' %}
{% block title %}Article Create with Form{% endblock %}

{% block header %}
    <h1>Article create form</h1>
{% endblock %}

{% block content %}
    <div>
     {% block primary_link %}
          {{ block.super }}
          <span>Article create form</span>
      {% endblock %}
    </div>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary">Save</button>
    </form>
{% endblock %}

templates/article/create.html
{% extends 'base.html' %}

{% block title %}Article Create{% endblock %}

{% block header %}
    <h1 class="mt-3">Create page</h1>
{% endblock %}

{% block content %}
    <div>
     {% block primary_link %}
          {{ block.super }}
          <span>Article create</span>
      {% endblock %}
    </div>
    {% if created %}
    <div>
        <span>
            <a href="{% url 'article:article_list' %}">Articles</a>
        </span> /
        <span>
            <a href="{% url 'article:create' %}">+ add new one</a>
        </span>
    </div>
        <h1>{{ object.title }}</h1>
        <p>{{ object.content }}</p>
    {% else %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div>
            <div>
                <label for="title">Title</label>
            </div>

            <input class="form-control" name="title" placeholder="title" id="title">
        </div>
        <div>
            <div>
                <label for="content">Content</label>
            </div>
            <textarea class="form-control" name="content" id="content" placeholder="Content"></textarea>
        </div>
        <div>
            <div>
                <label for="image">Image</label>
            </div>
            <input class="form-control" type="file" name="image" id="image" placeholder="image">
        </div>
        <button type='submit' class="btn btn-primary mt-3">ADD</button>
    </form>
    {% endif %}

{% endblock %}

templates/article/delete.html
{% extends 'base.html' %}

{% block title %}Article detail{% endblock %}

{% block header %}
    <h1 class="mt-3">Article delete</h1>
{% endblock %}

{% block content %}
    <div>
     {% block primary_link %}
          {{ block.super }}
          <span>Article delete</span>
      {% endblock %}
    </div>

<h2>Are you sure to delete "{{ object.title }}"</h2>
<form class="mt-3" method="post">
    {% csrf_token %}
    <button class="btn btn-primary" type="submit">Delete</button>
    <a class="btn btn-secondary" href="{% url 'article:article_list' %}">No, thanks</a>
</form>
{% endblock %}

templates/article/detail.html
{% extends '../base.html' %}
{% block title %}
    Try django detail
{% endblock %}

{% block header %}
    <h1 class="fs-1 mt-3">Article detail</h1>
{% endblock %}

{% block content %}
    <div>
     {% block primary_link %}
          {{ block.super }}
          <span>Article detail</span>
      {% endblock %}
    </div>
    <div class="mt-5">
    {% if object_detail.image %}
        <img height="200" src="{{ object_detail.image.url }}" alt="">
    {% endif %}
    <h1>{{ object_detail.title }}</h1>
    <p>{{ object_detail.content }}</p>
    <div>
        <a class="btn btn-success" href="{% url 'article:change' object_detail.id %}">Edit</a>
        <a class="btn btn-danger" href="{% url 'article:delete' object_detail.id %}">Delete</a>
    </div>
    </div>
{% endblock %}

templates/article/edit.html
{% extends 'base.html' %}
{% block title %}Article edit{% endblock %}

{% block header %}
    <h1 class="mt-3">Edit article</h1>
{% endblock %}

{% block content %}
    <div class="mt-3">
     {% block primary_link %}
          {{ block.super }}
          <span>Article edit</span>
      {% endblock %}
    </div>
<div class="mt-3">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <pre>
            <code>Modified date: {{ object.modified_at }}</code>
            <code>Created date: {{ object.created_at }}</code>
        </pre>
        <button class="btn btn-secondary" type="submit">Save</button>
    </form>
</div>
{% endblock %}

templates/article/index.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
    <h1 class="my-3">Article list</h1>
{% endblock %}
{% block content %}
    <div>
        <span class="fs-3 mb-5">{{ old_articles_list.count }} from {{ object_list.count }} object(s) found</span>
    </div>
    <table class="table mt-3">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Title</th>
                <th scope="col">Content</th>
                <th scope="col">Edit</th>
                <th scope="col">Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for i in object_list %}
                <tr>
                    <th scope="row">{{ i.id }}</th>
                    <th><a class="text-success text-decoration-none" href="{% url 'article:article_detail' i.slug %}">{{ i.title }}</a></th>
                    <th>{{ i.content }}</th>
                    <th><a class="btn btn-success" href="{% url 'article:change' i.id %}">Edit</a></th>
                    <th><a class="btn btn-danger" href="{% url 'article:delete' i.id %}">Delete</a></th>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="pagination">
        <span class="step-links">
            {% if object_list.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ object_list.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
            </span>

            {% if object_list.has_next %}
                <a href="?page={{ object_list.next_page_number }}">next</a>
                <a href="?page={{ object_list.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endblock %}